blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/sikka-software/hawa/discussions
    about: Ask questions and discuss with other community members
  - name: ğŸ’¡ Feature request
    url: https://github.com/sikka-software/hawa/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
